version: "3.9"
services:
  backend:
    build: ./api_server
    volumes:
      - ./api_server:/api_server
    ports:
      - 8001:8000
    env_file: ./api_server/.env.development
    tty: true
    stdin_open: true
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3001:3000
  db:
    image: mysql:8.0.28
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reading_record_dev
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4567:4566
    environment:
      - SERVICES=s3
    volumes:
      - ./localstack:/etc/localstack/init/ready.d
